services:
  moderation:
    container_name: moderation-service
    restart: unless-stopped
    env_file: ./moderation-service/.env
    ports:
      - "3001:3001"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    build:
      dockerfile: ./moderation-service/Dockerfile
