services:
  moderation:
    container_name: moderation-service
    restart: no
    ports:
      - "3001:3001"
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
    build:
      dockerfile: ./moderation-service/Dockerfile
    environment:
      - MONGODB_URI
      - SENTRY_DSN
      - ENVIRONMENT
      - MODERATION_LENGTH_IN_S
